// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Scanner.flex


import java.io.*;
import java.util.*;


@SuppressWarnings("fallthrough")
public class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\1\22\0\1\1\1\3"+
    "\1\4\1\5\1\0\1\6\1\7\1\10\2\11\1\12"+
    "\1\13\1\11\1\14\1\15\1\16\12\17\2\11\1\20"+
    "\1\21\1\20\2\0\4\22\1\23\25\22\1\11\1\24"+
    "\1\11\1\0\1\25\1\0\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\25\1\34\1\35\1\25\1\36\1\37"+
    "\1\25\1\40\1\41\1\42\1\25\1\43\1\44\1\45"+
    "\1\46\5\25\1\11\1\47\1\11\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\1\1\5"+
    "\1\6\4\4\1\7\1\10\1\11\1\12\14\13\1\1"+
    "\1\10\1\0\1\14\1\15\1\0\1\16\1\17\1\3"+
    "\2\5\1\0\1\11\1\20\1\21\1\0\1\12\15\13"+
    "\1\0\1\5\1\22\1\0\1\23\1\12\14\13\1\24"+
    "\1\23\1\0\1\12\4\13\1\25\4\13\1\26\1\23"+
    "\1\0\1\23\1\12\5\13\1\23\1\12\2\13\1\23"+
    "\1\12\1\23\1\12\1\27\1\12\1\27\1\12\1\27"+
    "\1\12\1\27\1\12\1\27\1\12\1\27\1\12\1\27"+
    "\1\12\1\27\1\12\1\27\1\12\1\27\1\12\1\27"+
    "\1\12\1\27\1\12\1\27\1\12\1\27\1\12\1\27"+
    "\1\12\1\27\1\12\1\27\1\12\1\27\1\12\1\27"+
    "\1\12\1\27\1\12\1\27\1\12\1\27\1\12\1\27"+
    "\1\12\1\27\1\0\1\27\1\30\23\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\50\0\360"+
    "\0\u0118\0\50\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\170"+
    "\0\170\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8"+
    "\0\u0320\0\u0348\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410\0\50"+
    "\0\240\0\50\0\50\0\u0438\0\u0460\0\u0488\0\50\0\u04b0"+
    "\0\50\0\u04d8\0\50\0\50\0\50\0\u0500\0\u0528\0\u0550"+
    "\0\u0578\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690"+
    "\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758\0\u0780\0\50\0\u07a8"+
    "\0\u07d0\0\u07f8\0\u0820\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8"+
    "\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0\0\u09d8\0\50\0\u0a00"+
    "\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0230\0\u0b18"+
    "\0\u0b40\0\u0b68\0\u0b90\0\u0230\0\u0bb8\0\u0be0\0\u0be0\0\u0c08"+
    "\0\u0c30\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48"+
    "\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\u0e38\0\u0e60\0\u0e88"+
    "\0\u0eb0\0\u0ed8\0\u0f00\0\u0f28\0\u0f50\0\u0f78\0\u0fa0\0\u0fc8"+
    "\0\u0ff0\0\u1018\0\u1040\0\u1068\0\u1090\0\u10b8\0\u10e0\0\u1108"+
    "\0\u1130\0\u1158\0\u1180\0\u11a8\0\u11d0\0\u11f8\0\u1220\0\u1248"+
    "\0\u1270\0\u1298\0\u12c0\0\u12e8\0\u1310\0\u1338\0\u1360\0\u1388"+
    "\0\u13b0\0\u13d8\0\u1400\0\u1428\0\u1450\0\u1478\0\u14a0\0\u14c8"+
    "\0\u14f0\0\u1518\0\u1540\0\u1568\0\u1590\0\u15b8\0\u1590\0\u15e0"+
    "\0\u1608\0\u1630\0\u1658\0\u1680\0\u16a8\0\u16d0\0\u16f8\0\u1720"+
    "\0\u1748\0\u1770\0\u1798\0\u17c0\0\u17e8\0\u1810\0\u1838\0\u1860"+
    "\0\u1888\0\50";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\2\1\16\1\17\1\20"+
    "\1\21\2\22\1\2\2\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\23\1\31\1\23\1\32\1\23\1\33\1\23"+
    "\1\34\1\35\1\36\1\23\1\37\51\0\2\3\66\0"+
    "\1\40\26\0\2\41\1\42\1\41\1\43\17\41\1\44"+
    "\23\41\5\0\1\45\4\0\1\46\44\0\1\47\40\0"+
    "\2\50\1\0\5\50\1\51\13\50\1\52\23\50\12\0"+
    "\1\7\6\0\1\53\41\0\1\54\3\0\1\17\1\0"+
    "\1\53\42\0\1\55\2\0\1\17\1\0\1\53\47\0"+
    "\1\53\43\0\1\56\1\0\1\17\47\0\1\57\5\0"+
    "\22\57\20\0\1\23\2\0\2\23\1\0\22\23\20\0"+
    "\1\23\2\0\2\23\1\0\16\23\1\60\3\23\20\0"+
    "\1\23\2\0\2\23\1\0\14\23\1\61\5\23\20\0"+
    "\1\23\2\0\2\23\1\0\5\23\1\62\14\23\20\0"+
    "\1\23\2\0\2\23\1\0\12\23\1\63\7\23\20\0"+
    "\1\23\2\0\2\23\1\0\1\23\1\64\6\23\1\65"+
    "\10\23\1\66\20\0\1\23\2\0\2\23\1\0\13\23"+
    "\1\67\6\23\20\0\1\23\2\0\2\23\1\0\14\23"+
    "\1\70\5\23\20\0\1\23\2\0\2\23\1\0\21\23"+
    "\1\71\20\0\1\23\2\0\2\23\1\0\5\23\1\72"+
    "\14\23\20\0\1\23\2\0\2\23\1\0\20\23\1\73"+
    "\1\23\20\0\1\23\2\0\2\23\1\0\16\23\1\74"+
    "\3\23\50\0\1\47\4\0\1\41\17\0\1\41\13\0"+
    "\1\41\2\0\1\41\1\0\1\41\2\0\2\45\1\0"+
    "\45\45\12\46\1\75\35\46\2\76\1\0\5\76\1\77"+
    "\13\76\1\100\23\76\10\0\1\50\13\0\1\50\13\0"+
    "\1\50\2\0\1\50\1\0\1\50\21\0\1\101\47\0"+
    "\1\102\5\0\22\102\20\0\1\23\2\0\2\23\1\0"+
    "\5\23\1\103\14\23\20\0\1\23\2\0\2\23\1\0"+
    "\13\23\1\104\6\23\20\0\1\23\2\0\2\23\1\0"+
    "\3\23\1\105\16\23\20\0\1\23\2\0\2\23\1\0"+
    "\17\23\1\106\2\23\20\0\1\23\2\0\2\23\1\0"+
    "\12\23\1\107\7\23\20\0\1\23\2\0\2\23\1\0"+
    "\13\23\1\110\6\23\20\0\1\23\2\0\2\23\1\0"+
    "\13\23\1\111\6\23\20\0\1\23\2\0\2\23\1\0"+
    "\15\23\1\112\4\23\20\0\1\23\2\0\2\23\1\0"+
    "\14\23\1\113\5\23\20\0\1\23\2\0\2\23\1\0"+
    "\20\23\1\67\1\23\20\0\1\23\2\0\2\23\1\0"+
    "\20\23\1\114\1\23\20\0\1\23\2\0\2\23\1\0"+
    "\1\23\1\115\20\23\20\0\1\23\2\0\2\23\1\0"+
    "\21\23\1\116\1\0\5\46\1\117\4\46\1\75\35\46"+
    "\2\76\1\0\5\76\1\51\13\76\1\100\23\76\10\0"+
    "\1\76\13\0\1\76\13\0\1\76\2\0\1\76\1\0"+
    "\1\76\21\0\1\120\3\0\1\121\6\0\1\121\34\0"+
    "\1\122\5\0\22\122\20\0\1\23\2\0\2\23\1\0"+
    "\1\23\1\123\20\23\20\0\1\23\2\0\2\23\1\0"+
    "\4\23\1\124\13\23\1\125\1\23\20\0\1\23\2\0"+
    "\2\23\1\0\12\23\1\126\7\23\20\0\1\23\2\0"+
    "\2\23\1\0\5\23\1\127\14\23\20\0\1\23\2\0"+
    "\2\23\1\0\17\23\1\116\2\23\20\0\1\23\2\0"+
    "\2\23\1\0\10\23\1\130\11\23\20\0\1\23\2\0"+
    "\2\23\1\0\3\23\1\131\16\23\20\0\1\23\2\0"+
    "\2\23\1\0\21\23\1\132\20\0\1\23\2\0\2\23"+
    "\1\0\15\23\1\127\4\23\20\0\1\23\2\0\2\23"+
    "\1\0\21\23\1\133\20\0\1\23\2\0\2\23\1\0"+
    "\16\23\1\132\3\23\20\0\1\23\2\0\2\23\1\0"+
    "\5\23\1\134\14\23\20\0\1\135\3\0\1\121\6\0"+
    "\1\121\30\0\2\136\2\0\1\137\47\0\1\140\5\0"+
    "\22\140\20\0\1\23\2\0\2\23\1\0\11\23\1\127"+
    "\10\23\20\0\1\23\2\0\2\23\1\0\10\23\1\131"+
    "\11\23\20\0\1\23\2\0\2\23\1\0\10\23\1\141"+
    "\11\23\20\0\1\23\2\0\2\23\1\0\1\23\1\142"+
    "\20\23\20\0\1\23\2\0\2\23\1\0\17\23\1\143"+
    "\2\23\20\0\1\23\2\0\2\23\1\0\20\23\1\144"+
    "\1\23\20\0\1\23\2\0\2\23\1\0\20\23\1\127"+
    "\1\23\20\0\1\23\2\0\2\23\1\0\16\23\1\145"+
    "\3\23\20\0\1\146\3\0\1\121\6\0\1\121\34\0"+
    "\1\137\47\0\1\147\5\0\22\147\20\0\1\23\2\0"+
    "\2\23\1\0\13\23\1\150\6\23\20\0\1\23\2\0"+
    "\2\23\1\0\16\23\1\106\3\23\20\0\1\23\2\0"+
    "\2\23\1\0\7\23\1\127\12\23\20\0\1\23\2\0"+
    "\2\23\1\0\10\23\1\151\11\23\20\0\1\23\2\0"+
    "\2\23\1\0\13\23\1\127\6\23\20\0\1\152\3\0"+
    "\1\121\6\0\1\121\34\0\1\153\5\0\22\153\20\0"+
    "\1\23\2\0\2\23\1\0\21\23\1\106\20\0\1\23"+
    "\2\0\2\23\1\0\14\23\1\145\5\23\20\0\1\154"+
    "\3\0\1\121\6\0\1\121\34\0\1\155\5\0\22\155"+
    "\20\0\1\156\3\0\1\121\6\0\1\121\34\0\1\157"+
    "\5\0\22\157\20\0\1\160\47\0\1\161\5\0\22\161"+
    "\20\0\1\162\47\0\1\163\5\0\22\163\20\0\1\164"+
    "\47\0\1\165\5\0\22\165\20\0\1\166\47\0\1\167"+
    "\5\0\22\167\20\0\1\170\47\0\1\171\5\0\22\171"+
    "\20\0\1\172\47\0\1\173\5\0\22\173\20\0\1\174"+
    "\47\0\1\175\5\0\22\175\20\0\1\176\47\0\1\177"+
    "\5\0\22\177\20\0\1\200\47\0\1\201\5\0\22\201"+
    "\20\0\1\202\47\0\1\203\5\0\22\203\20\0\1\204"+
    "\47\0\1\205\5\0\22\205\20\0\1\206\47\0\1\207"+
    "\5\0\22\207\20\0\1\210\47\0\1\211\5\0\22\211"+
    "\20\0\1\212\47\0\1\213\5\0\22\213\20\0\1\214"+
    "\47\0\1\215\5\0\22\215\20\0\1\216\47\0\1\217"+
    "\5\0\22\217\20\0\1\220\47\0\1\221\5\0\22\221"+
    "\20\0\1\222\47\0\1\223\5\0\22\223\20\0\1\224"+
    "\47\0\1\225\5\0\22\225\20\0\1\226\47\0\1\227"+
    "\5\0\22\227\20\0\1\230\47\0\1\231\5\0\22\231"+
    "\20\0\1\232\47\0\1\233\5\0\22\233\20\0\1\234"+
    "\47\0\1\235\5\0\22\235\20\0\1\236\47\0\1\237"+
    "\5\0\22\237\20\0\1\240\47\0\1\241\47\0\1\242"+
    "\47\0\1\243\47\0\1\244\47\0\1\245\47\0\1\246"+
    "\47\0\1\247\47\0\1\250\47\0\1\251\47\0\1\252"+
    "\47\0\1\253\47\0\1\254\47\0\1\255\47\0\1\256"+
    "\47\0\1\257\47\0\1\260\47\0\1\261\47\0\1\262"+
    "\30\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6320];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\2\1\1\11\25\1\1\11"+
    "\1\0\2\11\1\0\2\1\1\11\1\1\1\11\1\0"+
    "\3\11\1\0\16\1\1\0\1\1\1\11\1\0\16\1"+
    "\1\11\1\1\1\0\14\1\1\0\76\1\1\0\24\1"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private int          whitespaceRemoved = 0;
    private int          linesProcessed    = 0;
    private SymbolTable  symbolTable       = new SymbolTable();
    private ErrorHandler errorHandler      = new ErrorHandler();  // Part 3

    private Token token(TokenType type) {
        // Track highest line number seen so far
        if (yyline + 1 > linesProcessed) linesProcessed = yyline + 1;
        return new Token(type, yytext(), yyline + 1, yycolumn + 1);
    }

    public int          getWhitespaceRemoved() { return whitespaceRemoved; }
    public int          getLinesProcessed()     { return linesProcessed;    }
    public SymbolTable  getSymbolTable()        { return symbolTable;       }
    public ErrorHandler getErrorHandler()       { return errorHandler;      }  // Part 3


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorHandler.detectInvalidChar(yytext().charAt(0), yyline+1, yycolumn+1);
                        return token(TokenType.ERROR);
            }
          // fall through
          case 25: break;
          case 2:
            { whitespaceRemoved += yytext().length();
                        if (yyline + 1 > linesProcessed) linesProcessed = yyline + 1;
                        return token(TokenType.WHITESPACE);
            }
          // fall through
          case 26: break;
          case 3:
            { return token(TokenType.LOGICAL_OP);
            }
          // fall through
          case 27: break;
          case 4:
            { return token(TokenType.ARITHMETIC_OP);
            }
          // fall through
          case 28: break;
          case 5:
            { errorHandler.detectUnterminatedChar(yytext(), yyline+1, yycolumn+1);
                        return token(TokenType.ERROR);
            }
          // fall through
          case 29: break;
          case 6:
            { return token(TokenType.PUNCTUATOR);
            }
          // fall through
          case 30: break;
          case 7:
            { return token(TokenType.INTEGER_LITERAL);
            }
          // fall through
          case 31: break;
          case 8:
            { return token(TokenType.RELATIONAL_OP);
            }
          // fall through
          case 32: break;
          case 9:
            { return token(TokenType.ASSIGNMENT_OP);
            }
          // fall through
          case 33: break;
          case 10:
            { symbolTable.insert(yytext(), yyline+1, yycolumn+1);
                        return token(TokenType.IDENTIFIER);
            }
          // fall through
          case 34: break;
          case 11:
            { errorHandler.detectInvalidIdentifier(yytext(), yyline+1, yycolumn+1);
                        return token(TokenType.ERROR);
            }
          // fall through
          case 35: break;
          case 12:
            { errorHandler.detectUnterminatedString(yytext(), yyline+1, yycolumn+1);
                        return token(TokenType.ERROR);
            }
          // fall through
          case 36: break;
          case 13:
            { return token(TokenType.STRING_LITERAL);
            }
          // fall through
          case 37: break;
          case 14:
            { return token(TokenType.SINGLE_LINE_COMMENT);
            }
          // fall through
          case 38: break;
          case 15:
            { errorHandler.detectUnclosedComment(yytext(), yyline+1, yycolumn+1);
                        return token(TokenType.ERROR);
            }
          // fall through
          case 39: break;
          case 16:
            { return token(TokenType.INCREMENT_OP);
            }
          // fall through
          case 40: break;
          case 17:
            { return token(TokenType.DECREMENT_OP);
            }
          // fall through
          case 41: break;
          case 18:
            { return token(TokenType.CHARACTER_LITERAL);
            }
          // fall through
          case 42: break;
          case 19:
            { return token(TokenType.FLOATING_POINT_LITERAL);
            }
          // fall through
          case 43: break;
          case 20:
            { return token(TokenType.MULTI_LINE_COMMENT);
            }
          // fall through
          case 44: break;
          case 21:
            { return token(TokenType.KEYWORD);
            }
          // fall through
          case 45: break;
          case 22:
            { return token(TokenType.BOOLEAN_LITERAL);
            }
          // fall through
          case 46: break;
          case 23:
            { errorHandler.detectMalformedFloat(yytext(), yyline+1, yycolumn+1);
                        int dotIndex = yytext().indexOf('.');
                        String valid = yytext().substring(0, dotIndex + 7);
                        return new Token(TokenType.FLOATING_POINT_LITERAL, valid, yyline+1, yycolumn+1);
            }
          // fall through
          case 47: break;
          case 24:
            { errorHandler.detectIdentifierTooLong(yytext(), yyline+1, yycolumn+1);
                        String truncated = yytext().substring(0, 31);
                        symbolTable.insert(truncated, yyline+1, yycolumn+1);
                        return new Token(TokenType.IDENTIFIER, truncated, yyline+1, yycolumn+1);
            }
          // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
